### ISSUE TITLE
List of broken modules

### ISSUE THREAD

**Issue by matty45** [MontagueM/HaloInfiniteModuleUnpacker#3]
These modules cannot be fully extracted as of now:
- /any/globals/globals-rtx-new.module
- /any/globals/multiplayer_r1-rtx-new.module
- /any/globals/forge/forge_objects-rtx-new.module
- /any/levels/multi/academy_weapon_drills/academy_weapon_drills-rtx-new.module
- /any/levels/multi/btb_drydock/btb_drydock-rtx-new.module
- /any/levels/multi/btb_fragmentation/btb_fragmentation-rtx-new.module
- /any/levels/multi/btb_highpower/btb_highpower-rtx-new.module
- /any/levels/multi/ctf_aquarius/ctf_aquarius-rtx-new.module
- /any/globals/common-rtx-new.module
- /any/levels/multi/ctf_bazaar/ctf_bazaar-rtx-new.module
- /any/levels/multi/sgh_blueprint/sgh_blueprint-rtx-new.module
- /any/levels/multi/sgh_streets/sgh_streets-rtx-new.module
- /any/levels/multi/va_behemoth/va_behemoth-rtx-new.module
- /any/levels/multi/va_launchsite/va_launchsite-rtx-new.module
- /any/levels/ui/mainmenu/mainmenu-rtx-new.module
- /pc/globals/common-rtx-new.module

The rest of the modules should extract fine

**Comment by matty45** [comment]
Here is the error that appears when extracting any of these modules:
`Traceback (most recent call last):
  File "F:\downloads\HIMU-main\unpacker.py", line 235, in <module>
    extract_module(module_name)
  File "F:\downloads\HIMU-main\unpacker.py", line 194, in extract_module
    tmp.seek(file_data_offset + block.comp_offset)
AttributeError: 'bytes' object has no attribute 'seek'`

**Comment by Coreforge** [comment]
I got /pc/globals/common-rtx-new.module to successfully extract. The local_data_offset seems to be somewhere between 5 and 7 bytes wide. The other files seem to be either truncated or missing _hd1 files

**Comment by matty45** [comment]
I made a fix over at https://github.com/matty45/HIMU but i have not made a pull request due to the fix being very hacky, allowing modules to extract, even if they have missing hd1 files that have been stripped from the game

**Comment by MontagueM** [comment]
Fixed
